version: '3.8'

services:
  
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  tasks:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - no-cache=true
    restart: on-failure
    platform: linux/x86_64
    ports:
     - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - SERVER_PORT=8080
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-data: