definitions:
  model.Task:
    properties:
      description:
        type: string
      due_date:
        type: string
      id:
        type: integer
      status:
        type: string
      title:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /tasks/{taskId}:
    get:
      description: Retrieve task by Id
      parameters:
      - description: Task ID
        in: path
        name: taskId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Task'
            type: array
      summary: Retrieve task by Id
      tags:
      - tasks
swagger: "2.0"
